version: '3'

services:
  db:
    image: postgres
    environment:
      - PGDATA=/db-data
    volumes:
      - db:/db-data
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:80 --settings=timestrap.settings.docker
    depends_on:
      - db
    environment:
      - SECRET_KEY=CHANGE-ME

volumes:
  db:
